#!/bin/sh

(automake-1.9 --version) < /dev/null > /dev/null 2>&1 || {
	echo;
	echo "You must have automake1.9 installed to compile blobby";
	echo;
	exit;
}

(autoconf --version) < /dev/null > /dev/null 2>&1 || {
	echo;
	echo "You must have autoconf installed to compile blobby";
	echo;
	exit;
}

echo "Generating configuration files for blobby, please wait..."
echo;

aclocal -I m4 $ACLOCAL_FLAGS \
&& automake-1.9 --gnu --add-missing --copy \
&& autoconf \
&& echo "You can now run ./configure"

