name: Build

on: [push, pull_request]

jobs:
  Build:
    name: "IOS"
    runs-on: macos-11

    steps:
      - name: Setup MacOS
        run: |
          brew install \
            sdl2 \
            physfs \
            boost
      - uses: actions/checkout@v2
      - name: Configure CMake and Build
        run: |
          cmake . -GXcode -DCMAKE_SYSTEM_NAME=iOS
          cmake --build .
